# classifier
learning_rate: 0.001

# trainer
max_epochs: 2
seed: 1234

# data
data_path: ./_data/data/jena_climate_2009_2016.csv
input_length: 24
label_length: 24

# network
hidden_size: 30

# logging
log_dir: ./logs/logging_/model
log_normal: log.log
log_error: error.log

# mlflow
experiment_name: model01
tracking_uri: logs/mlruns
user: vscode

# checkpoint
checkpoint_dir: ./logs/lightning/